# 1. Reshpae


In [3]:
import numpy as np
x =np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
x.shape #dimensiiones

(10,)

In [5]:
np.reshape(x, (2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
np.reshape(x, (5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
np.reshape(x,(10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [8]:
np.reshape(x,(-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
x.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# 2. Performance

In [14]:
from time import time

In [12]:
x = np.linspace(1,10000000,20000000)
b0= 5
b1 = 2

In [16]:
y = np.empty_like(x)
inicio = time()
for index, value in enumerate(x):
    y[index] = b0 + b1 *value
    
fin = time()

print("el tiempo total es:" , fin-inicio)

el tiempo total es: 9.446010828018188


In [17]:
x = np.arange(1,6,1)
x



array([1, 2, 3, 4, 5])

In [20]:
vect1 = np.ones_like(x).reshape((-1,1))
vect1

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [23]:
x = x.reshape((-1,1))
A= np.hstack([vect1, x])
A

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [24]:
betas = np.array([[b0],[b1]])

In [25]:
betas

array([[5],
       [2]])

In [29]:
inicio = time()
y1 = np.matmul(A, betas)
fin = time()
print("el tiempo total es: ",fin-inicio)

el tiempo total es:  0.0


In [27]:
y1

array([[ 7],
       [ 9],
       [11],
       [13],
       [15]])

# 3. Pandas - (Panel Data)

In [31]:
import numpy as np
import pandas as pd

pd.Series(np.random.rand(10))

0    0.837525
1    0.806540
2    0.131480
3    0.846549
4    0.923867
5    0.999222
6    0.064876
7    0.705756
8    0.147762
9    0.203146
dtype: float64

In [32]:
data = np.random.rand(10)

In [33]:
data


array([0.36240881, 0.38577986, 0.310852  , 0.31865868, 0.48118244,
       0.82959357, 0.91877348, 0.57537889, 0.95230985, 0.20312507])

In [35]:
pd.Series(data)

0    0.362409
1    0.385780
2    0.310852
3    0.318659
4    0.481182
5    0.829594
6    0.918773
7    0.575379
8    0.952310
9    0.203125
dtype: float64

In [38]:
pd.Series(data, index=np.arange(10,110,10))

10     0.362409
20     0.385780
30     0.310852
40     0.318659
50     0.481182
60     0.829594
70     0.918773
80     0.575379
90     0.952310
100    0.203125
dtype: float64

In [39]:
diccionario ={"a":30,"b":60,"C":"hola todos", "D":np.exp(5)}

In [40]:
diccionario

{'a': 30, 'b': 60, 'C': 'hola todos', 'D': 148.4131591025766}

In [41]:
pd.Series(diccionario)

a            30
b            60
C    hola todos
D    148.413159
dtype: object

In [42]:
d = { 'columnaA': [10, 20, 30, 40],
         'columnaB': pd.Series(['abc', 10.5, 34, 'xy']),
         'columnaC': pd.Series([10.45, 89.34, 90.76, 24.89])
     }

In [43]:
df1 = pd.DataFrame(d)

In [44]:
df1

columnaA columnaB  columnaC
0        10      abc     10.45
1        20     10.5     89.34
2        30       34     90.76
3        40       xy     24.89

In [46]:
type(df1["columnaA"])

pandas.core.series.Series

In [47]:
df1.columnaA

0    10
1    20
2    30
3    40
Name: columnaA, dtype: int64

In [49]:
df1[["columnaA","columnaC"]]

columnaA  columnaC
0        10     10.45
1        20     89.34
2        30     90.76
3        40     24.89

In [52]:
df1["columnaC"]

0    10.45
1    89.34
2    90.76
3    24.89
Name: columnaC, dtype: float64

In [56]:
#extraccion de informacion en base al nombre de fila(index) y la columna
df1.loc[[0,1,3],["columnaC","columnaA"]]

columnaC  columnaA
0     10.45        10
1     89.34        20
3     24.89        40

In [58]:
df1.iloc[[0,1,3,0],[2,0]] #indexa en funcion del indice

columnaC  columnaA
0     10.45        10
1     89.34        20
3     24.89        40
0     10.45        10

In [83]:
df1.loc[[0,2],["columnaB"]] #traer fila 0 y 2  con la columnaB

columnaB
0      abc
2       34

In [62]:
#columna nueva
df1["nueva"]=df1["columnaA"]+df1["columnaC"]
df1

columnaA columnaB  columnaC   nueva
0        10      abc     10.45   20.45
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76
3        40       xy     24.89   64.89

In [63]:
#eliminar elementos
#axis =0 -> operacmos sobre las filas
#axis =1 -> operamos sobre las columnas
# inplace = True ->modifica la variable orinal con la operacion aplicada
df1.drop(0,axis=0)

columnaA columnaB  columnaC   nueva
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76
3        40       xy     24.89   64.89

In [64]:
df1

columnaA columnaB  columnaC   nueva
0        10      abc     10.45   20.45
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76
3        40       xy     24.89   64.89

In [67]:
df1.drop("columnaA",axis=1)

columnaB  columnaC   nueva
0      abc     10.45   20.45
1     10.5     89.34  109.34
2       34     90.76  120.76
3       xy     24.89   64.89

In [68]:
df1

columnaA columnaB  columnaC   nueva
0        10      abc     10.45   20.45
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76
3        40       xy     24.89   64.89

In [70]:
df1.drop(3, axis=0, inplace=True) ## afecta la variable original

In [71]:
df1

columnaA columnaB  columnaC   nueva
0        10      abc     10.45   20.45
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76

# 3.1 Filtros

In [72]:
df2 = pd.DataFrame({
    'A': np.random.randint(1, 20, size=10),
    'B': np.random.randint(1, 20, size=10)
})

df2

A   B
0   3  12
1  10   2
2  18  15
3  13   5
4  17   6
5   8   8
6   5   5
7  10   8
8  13   7
9   5  19

In [73]:
df2[df2["A"]>10]

A   B
2  18  15
3  13   5
4  17   6
8  13   7

In [74]:
df2["A"]>10

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
8     True
9    False
Name: A, dtype: bool

In [77]:
df2[ (df2["A"]>7) & (df2["B"] <10) ]

A  B
1  10  2
3  13  5
4  17  6
5   8  8
7  10  8
8  13  7

# 3.2 Operacion de agregacion

In [84]:
df = pd.DataFrame({'col1': [10,20,30,40,50,60], 
                   'col2':[1,2,3,4,5,6], 
                   'col3':['A', 'B', 'C', 'D', 'A', 'F']})

df

col1  col2 col3
0    10     1    A
1    20     2    B
2    30     3    C
3    40     4    D
4    50     5    A
5    60     6    F

In [86]:
df["col1"].sum()

210

In [87]:
df.sum()

col1       210
col2        21
col3    ABCDAF
dtype: object

In [89]:
#axis=0 operacion sobre columnas
#acis =1 operacion sobre fila (indices)
df.sum(axis=0)

col1       210
col2        21
col3    ABCDAF
dtype: object

In [90]:
df[["col1","col2"]].sum(axis=1)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [91]:
#cuenta cantidad de filas en la columna
df["col2"].count()

6

In [92]:
# cuenta cantidad de ocurrencias de cada elemento
df["col3"].value_counts()

col3
A    2
B    1
C    1
D    1
F    1
Name: count, dtype: int64

In [94]:
#devuelve arreglo de numpy con valores de una columna
df["col2"].values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [95]:
#devuelve arreglo con nombres de columans
df.columns.values


array(['col1', 'col2', 'col3'], dtype=object)

# Anlytics con Pandas

In [97]:
dataset = pd.read_csv("hotel_bookings.csv")
dataset.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [98]:
dataset.shape

(119390, 32)

In [99]:
dataset.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             

In [101]:
dataset["is_canceled"].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [102]:
dataset["lead_time"].value_counts()

lead_time
0      6345
1      3460
2      2069
3      1816
4      1715
       ... 
400       1
370       1
532       1
371       1
463       1
Name: count, Length: 479, dtype: int64

In [103]:
#valor menor a 30 discreta
#valor mayor a 30 continuo