# 1.Sets

In [1]:
sett = {1,2,3,4,5,"hola"}

In [2]:
sett

{1, 2, 3, 4, 5, 'hola'}

In [4]:
sett.add(10) #agregar al set


In [5]:
sett

{1, 10, 2, 3, 4, 5, 'hola'}

In [7]:
sett.add(10)

In [8]:
sett

{1, 10, 2, 3, 4, 5, 'hola'}

In [9]:
set1 ={1,2,3,4,5}
set2 ={5,6,7,8,9,4}


In [10]:
set1.union(set2) #union

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [12]:
set1.intersection(set2) #interseccion

{4, 5}

In [13]:
set1.difference(set2) #Diferencia

{1, 2, 3}

In [15]:
set2.difference(set1)

{6, 7, 8, 9}

In [16]:
set1.symmetric_difference(set2) #diferencia simetrica

{1, 2, 3, 6, 7, 8, 9}

In [17]:
letras = {"abc","DFG","hij"}


In [18]:
letras

{'DFG', 'abc', 'hij'}

In [21]:
{l.upper() for l in letras } #devuelve un set

{'ABC', 'DFG', 'HIJ'}

# 2. Numpy

In [22]:
import numpy as np

In [23]:
x = [1,2,3,4,5,]

In [24]:
x


[1, 2, 3, 4, 5]

In [27]:
x =np.array([1,2,3,4,5,6], dtype="float")

In [28]:
x

array([1., 2., 3., 4., 5., 6.])

In [29]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
x=np.zeros((10,10))

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.zeros_like(x)

array([0., 0., 0., 0., 0., 0.])

In [40]:
#dimensiones del tensor
x.shape #cantidad de elementos que tiene cada dimension

(10, 10)

In [39]:
#rango del tensor
x.ndim #cantidad de dimensiones

2

In [41]:
x[2,1]

0.0

In [42]:
x = np.array([[[10, 20, 30, 40, 50], 
               [60, 70, 80, 90, 100]], 
               [[100, 200, 300, 400, 500], 
                [600, 700, 800, 900, 1000]]
            ])

In [43]:
x


array([[[  10,   20,   30,   40,   50],
        [  60,   70,   80,   90,  100]],

       [[ 100,  200,  300,  400,  500],
        [ 600,  700,  800,  900, 1000]]])

In [44]:
x.ndim

3

In [45]:
x.shape

(2, 2, 5)

In [46]:
x[0]

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [48]:
x[0,1,3]

90

In [49]:
x[1,1,4]

1000

In [50]:
v = np.arange(1,6,1)

In [51]:
v

array([1, 2, 3, 4, 5])

In [52]:
w = np.arange(6,11,1)

In [53]:
print(v+w)

[ 7  9 11 13 15]


In [54]:
w

array([ 6,  7,  8,  9, 10])

In [57]:
print(v-w)
print(v*w)
print(v/w)

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [59]:
#broadcasting
v*2


array([ 2,  4,  6,  8, 10])

In [60]:
print(v/2)
print(v+5)
print(v-10)
print(v%2)

[0.5 1.  1.5 2.  2.5]
[ 6  7  8  9 10]
[-9 -8 -7 -6 -5]
[1 0 1 0 1]


In [61]:
# en listas normales no puede hacer broadcasting

x = [1,2,3]
x+2

TypeError: can only concatenate list (not "int") to list

### 2.3 Funciones universales 

In [62]:
x = np.array([-2,-1,0,1,1,3,6])

In [63]:
x

array([-2, -1,  0,  1,  1,  3,  6])

In [64]:
print(np.sign(x))

[-1 -1  0  1  1  1  1]


In [71]:
print(np.abs(x))
print(np.cos(x))
print(np.sin(x))
print(np.exp(x))
print(np.log(x))

[2 1 0 1 1 3 6]
[-0.41614684  0.54030231  1.          0.54030231  0.54030231 -0.9899925
  0.96017029]
[-0.90929743 -0.84147098  0.          0.84147098  0.84147098  0.14112001
 -0.2794155 ]
[1.35335283e-01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 2.71828183e+00 2.00855369e+01 4.03428793e+02]
[       nan        nan       -inf 0.         0.         1.09861229
 1.79175947]


C:\Users\XPRS\AppData\Local\Temp\ipykernel_14564\1468565477.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))
C:\Users\XPRS\AppData\Local\Temp\ipykernel_14564\1468565477.py:5: RuntimeWarning: invalid value encountered in log
  print(np.log(x))


In [72]:
print(np.log(x)[0])

nan


C:\Users\XPRS\AppData\Local\Temp\ipykernel_14564\1916674522.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(x)[0])
C:\Users\XPRS\AppData\Local\Temp\ipykernel_14564\1916674522.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(x)[0])


In [73]:
print(np.sqrt(x))

[       nan        nan 0.         1.         1.         1.73205081
 2.44948974]


C:\Users\XPRS\AppData\Local\Temp\ipykernel_14564\2965746161.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(x))


In [74]:
x = np.array([1,2,3,4,5,6,7,8,9,2,2])
x_nan = np.array([1,2,3,4, np.nan, 6, 8, 10, np.nan])

In [75]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 2])

In [76]:
x_nan

array([ 1.,  2.,  3.,  4., nan,  6.,  8., 10., nan])

In [77]:
np.mean(x) ## sacar la media

4.454545454545454

In [79]:
np.nanmean(x_nan) ## media para los casos donde hay nan

4.857142857142857

In [81]:
np.mean(x_nan)

nan

In [82]:
np.max(x)

9

In [85]:
print(np.max(x))
print(np.nanmax(x_nan))

9
10.0


In [86]:
print(np.min(x))
print(np.nanmin(x_nan))

1
1.0


In [87]:
print(np.var(x))
print(np.nanvar(x_nan))

6.793388429752068
9.26530612244898


In [88]:
print(np.std(x))
print(np.nanstd(x_nan))

2.6064129430602643
3.0438965360946453


In [89]:
print(np.prod(x))
print(np.nanprod(x_nan))

1451520
11520.0


In [90]:
print(np.argmax(x))
print(np.nanargmax(x_nan))

8
7


In [91]:
print(np.argmin(x)) #posicion del valor mas pequeño
print(np.nanargmin(x_nan))

0
0


In [92]:
print(np.median(x))
print(np.nanmedian(x_nan))

4.0
4.0
